### ISSUE TITLE
BlitzBasic / Blitz3D

### ISSUE THREAD

**Issue by Teddy55Codes** [CalculationCollective/.github#59]
B3DCalculator

**Comment by Janik313** [comment]
The B3D file format is used for 3d models (https://docs.fileformat.com/3d/b3d/).
I changed the name and file format of this calculator to BlitzMax (.bmx)

**Comment by Nyyks** [comment]
The B3D file format is only used for 3d models (https://docs.fileformat.com/3d/b3d/), thats why i changed the name to BBCalculator.

**Comment by Nyyks** [comment]
https://github.com/CalculationCollective/BBCalculator
